name: Build and Push Docker

on:
  push:
    branches: [main]
#    paths:
#      - 'src/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.hamza_FL }}

      - name: lowering case of repo
        run: echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: lowering case of owner
        run: echo "OWNER_LOWER=$(echo ${{ github.owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Print Repository Lowercase
        run: echo "Repository Lowercase: ${{ env.REPO_LOWER }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: hamza-karim/FL-client:latest
          build-args: REPO_URL=https://github.com/${{ env.OWNER_LOWER }}/${{ env.REPO_LOWER }}
          platforms: linux/amd64,linux/arm64/v8