name: Publish image to Docker Hub Client
on:
  workflow_dispatch:  # Triggered manually
#  push:
#    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u hamzakarim07 -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./FL_client/docker/Dockerfile
          push: true
          tags: hamzakarim07/flwr_client:latest
#          platforms: linux/amd64,linux/arm64/v8
          platforms: linux/arm64  # Limit the build to ARM64 architecture
